name: 'Install Scoop'
description: 'Installs the Scoop Installer'
inputs:
  debug:
    required: false
    default: false
  allow-install-as-admin:
    required: false
    default: true
  extension:
    required: false
    default: 'ps1'
runs:
  using: 'node16'
  main: 'src/index.js'
