# This is a basic workflow to help you get started with Actions

name: Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --add user.name "Github Actions"
          git config --add user.email "ninja@thesharp.ninja"

          npm install typescript -g
          npm install && npm run build && npm run bundle
          git add bundle/bundle.js
          git commit -m "Built bundle"
          
          gh repo sync

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
